---
title: "EcoZone Selection"
author: "Anna Talucci"
date: "10/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview



# Library

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(purrr)
library(readr)
library(cowplot)
library(ggcorrplot)
library(sp)
library(sf)
library(rgdal) # geospatial data
library(raster)
library(rgeos) # GIS Geometry
library(foreign) # deals with dbf files
```

# Data
```{r}
ecozone = st_read("../data/wwf_ecozone/wwf_terr_ecos_oRn.shp", "wwf_terr_ecos_oRn") 
```

```{r}
head(ecozone)
```

```{r}
biome = ecozone %>% filter(BIOME==11)
```

```{r}
unique(biome$ECO_NAME)
```

Cherskii-Kolyma mountain tundra 
Northeast Siberian coastal tundra 
Chukchi Peninsula tundra
Northeast Siberian taiga
Bering tundra
Taimyr-Central Siberian tundra
```{r}
target = c("Cherskii-Kolyma mountain tundra", "Northeast Siberian coastal tundra","Chukchi Peninsula tundra", "Northeast Siberian taiga", "Bering tundra", "Taimyr-Central Siberian tundra")
```

```{r}
ne_subset = ecozone %>% filter(ECO_NAME %in% target) 
```

```{r}
summary(ne_subset)
```


```{r}
plot(ne_subset$geometry)
```
```{r}
st_write(ne_subset, "../outputs/ecozones/ne_siberia_ecozones.shp", driver="ESRI Shapefile") 
```