---
title: "Add Attributes for snow off and climate"
author: "Anna Talucci"
date: "4/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview

add snow off and climate data to fire perimeters

# Clear workspace

```{r}
rm(list=ls()) 
```

# Packages

```{r include=FALSE}
library(sp)
library(sf)
library(rgdal) # geospatial data
library(raster)
library(rgeos) # GIS Geometry
library(foreign) # deals with dbf files
library(dplyr)
library(tidyr)
library(spatialEco)
library(ggplot2)
library(lubridate)
```

# Projections

WGS 84 need for gee
```{r}
wgs_proj =  "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs "
```

Equal Area projection for russia need for buffering hotspot data
https://gis.stackexchange.com/questions/264093/projection-for-russia-map

+proj=aea +lat_1=50 +lat_2=70 +lat_0=56 +lon_0=100 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs 

```{r}
ee_russia = "+proj=aea +lat_1=50 +lat_2=70 +lat_0=56 +lon_0=100 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs "
```


# Data

## Fire perimeters

```{r}
fires = st_read("../data/GEE-Attribute-Shapefiles/ru-fires-2001.shp", "ru-fires-2001") 
```

## Snow off
```{r}
snow = read.csv("../data/snow-off/2001_snow_off.csv") 
```

```{r}
head(snow)
```

```{r}
snow_data = snow %>% dplyr::select(ID_obj, relDoy, snowCover)
head(snow_data)
```

```{r}
snow %>% filter(ID_obj == 24)

```

```{r}
left_join(fires, snow_data, by="ID_obj")
```