---
title: "Monthly Weather"
author: "Anna Talucci"
date: "6/8/2021"
output: html_document
---

# Clear workspace

```{r}
rm(list=ls()) 
```


# Overview
[Terra Climate](https://developers.google.com/earth-engine/datasets/catalog/IDAHO_EPSCOR_TERRACLIMATE#bands)

Name    |	Units   |	Min	  |  Max   |	Scale	    | Description
def	    |   mm	  |   0*  |  4548* |	0.1	      | Climate water deficit, derived using a one-dimensional soil water balance model
pdsi    |		       | -4317*	| 3418*	| 0.01	     |Palmer Drought Severity Index

pr      |	mm	    |0*	      |7245*	|	         |Precipitation accumulation
tmmx	 |  °C	    |-670*	  | 576*	| 0.1	     |Maximum temperature

# Packages


```{r include=FALSE}

library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)

```




# Data 



```{r}
mw01 = read.csv("../data/MonthlyWeather/2013_meanMonth.csv") 
```

```{r}
mw = read.csv("../data/MonthlyWeatherEco/2013_meanMonthEco.csv") 
```




```{r}
head(mw01)

```





```{r}
data1 = mw01 %>% rename(def_01=X201301_def, 
                pdsi_01=X201301_pdsi, 
                pr_01=X201301_pr, 
                tmmx_01=X201301_tmmx, 
                def_02=X201302_def, 
                pdsi_02=X201302_pdsi, 
                pr_02=X201302_pr, 
                tmmx_02=X201302_tmmx, 
                def_03=X201303_def, 
                pdsi_03=X201303_pdsi, 
                pr_03=X201303_pr, 
                tmmx_03=X201303_tmmx,
                def_04=X201304_def, 
                pdsi_04=X201304_pdsi, 
                pr_04=X201304_pr, 
                tmmx_04=X201304_tmmx,
                def_05=X201305_def, 
                pdsi_05=X201305_pdsi, 
                pr_05=X201305_pr, 
                tmmx_05=X201305_tmmx,
                def_06=X201306_def, 
                pdsi_06=X201306_pdsi, 
                pr_06=X201306_pr, 
                tmmx_06=X201306_tmmx,
                def_07=X201307_def, 
                pdsi_07=X201307_pdsi, 
                pr_07=X201307_pr, 
                tmmx_07=X201307_tmmx,
                def_08=X201308_def, 
                pdsi_08=X201308_pdsi, 
                pr_08=X201308_pr, 
                tmmx_08=X201308_tmmx,
                def_09=X201309_def, 
                pdsi_09=X201309_pdsi, 
                pr_09=X201309_pr, 
                tmmx_09=X201309_tmmx,
                def_10=X201310_def, 
                pdsi_10=X201310_pdsi, 
                pr_10=X201310_pr, 
                tmmx_10=X201310_tmmx,
                def_11=X201311_def, 
                pdsi_11=X201311_pdsi, 
                pr_11=X201311_pr, 
                tmmx_11=X201311_tmmx) 

data1
```

```{r}
data2 = data1 %>%
 pivot_longer(
   cols = c("def_01", "pdsi_01", "pr_01", "tmmx_01", "def_02",  "pdsi_02", "pr_02" ,"tmmx_02", "def_03", "pdsi_03", "pr_03", "tmmx_03","def_04", "pdsi_04",  "pr_04", "tmmx_04", "def_05",  "pdsi_05", "pr_05", "tmmx_05", "def_06", "pdsi_06", "pr_06",  "tmmx_06", "def_07", "pdsi_07", "pr_07", "tmmx_07", "def_08", "pdsi_08", "pr_08",  "tmmx_08", "def_09", "pdsi_09", "pr_09", "tmmx_09","def_10", "pdsi_10", "pr_10", "tmmx_10", "def_11", "pdsi_11",  "pr_11","tmmx_11")  ,
   names_to = "wm",
   values_to = "measures") %>%
  dplyr::select(EcoCode:SIZEha, wm, measures) %>%
  separate(wm, c("weather", "month")) %>%
  pivot_wider(names_from = weather, values_from = measures)

data2
```

```{r}
data3 = data2 %>%
  mutate(def1=round(def*0.1,3)) %>%
  mutate(pdsi1=round(pdsi*0.01, 3)) %>%
  mutate(tmmx1=round(tmmx*0.1,3)) %>%
  dplyr::select(EcoCode:month, pr, def1, tmmx1) %>%
  rename(def=def1, tmmx=tmmx1)

data3
  
   
```


```{r}
write.csv(data3, '../outputs/CleanWeather/2013_MeanMonth.csv',  row.names = FALSE)
```

# By Ecozone

```{r}
mw = read.csv("../data/MonthlyWeatherEco/2013_meanMonthEco.csv") 
```




```{r}
head(mw)

```





```{r}
data4 = mw %>% rename(def_01=X201301_def, 
                pdsi_01=X201301_pdsi, 
                pr_01=X201301_pr, 
                tmmx_01=X201301_tmmx, 
                def_02=X201302_def, 
                pdsi_02=X201302_pdsi, 
                pr_02=X201302_pr, 
                tmmx_02=X201302_tmmx, 
                def_03=X201303_def, 
                pdsi_03=X201303_pdsi, 
                pr_03=X201303_pr, 
                tmmx_03=X201303_tmmx,
                def_04=X201304_def, 
                pdsi_04=X201304_pdsi, 
                pr_04=X201304_pr, 
                tmmx_04=X201304_tmmx,
                def_05=X201305_def, 
                pdsi_05=X201305_pdsi, 
                pr_05=X201305_pr, 
                tmmx_05=X201305_tmmx,
                def_06=X201306_def, 
                pdsi_06=X201306_pdsi, 
                pr_06=X201306_pr, 
                tmmx_06=X201306_tmmx,
                def_07=X201307_def, 
                pdsi_07=X201307_pdsi, 
                pr_07=X201307_pr, 
                tmmx_07=X201307_tmmx,
                def_08=X201308_def, 
                pdsi_08=X201308_pdsi, 
                pr_08=X201308_pr, 
                tmmx_08=X201308_tmmx,
                def_09=X201309_def, 
                pdsi_09=X201309_pdsi, 
                pr_09=X201309_pr, 
                tmmx_09=X201309_tmmx,
                def_10=X201310_def, 
                pdsi_10=X201310_pdsi, 
                pr_10=X201310_pr, 
                tmmx_10=X201310_tmmx,
                def_11=X201311_def, 
                pdsi_11=X201311_pdsi, 
                pr_11=X201311_pr, 
                tmmx_11=X201311_tmmx) 

data4
```

```{r}
data5 = data4 %>%
 pivot_longer(
   cols = c("def_01", "pdsi_01", "pr_01", "tmmx_01", "def_02",  "pdsi_02", "pr_02" ,"tmmx_02", "def_03", "pdsi_03", "pr_03", "tmmx_03","def_04", "pdsi_04",  "pr_04", "tmmx_04", "def_05",  "pdsi_05", "pr_05", "tmmx_05", "def_06", "pdsi_06", "pr_06",  "tmmx_06", "def_07", "pdsi_07", "pr_07", "tmmx_07", "def_08", "pdsi_08", "pr_08",  "tmmx_08", "def_09", "pdsi_09", "pr_09", "tmmx_09","def_10", "pdsi_10", "pr_10", "tmmx_10", "def_11", "pdsi_11",  "pr_11","tmmx_11")  ,
   names_to = "wm",
   values_to = "measures") %>%
  dplyr::select(ECO_NAME, eco_code, OBJECTID, wm, measures) %>%
  separate(wm, c("weather", "month")) %>%
  pivot_wider(names_from = weather, values_from = measures)

data5
```

```{r}
data6 = data5 %>%
  mutate(def1=round(def*0.1,3)) %>%
  mutate(pdsi1=round(pdsi*0.01, 3)) %>%
  mutate(tmmx1=round(tmmx*0.1,3)) %>%
  dplyr::select(ECO_NAME, eco_code, OBJECTID, pr, def1, tmmx1) %>%
  rename(def=def1, tmmx=tmmx1)

data6
  
   
```


```{r}
write.csv(data6, '../outputs/CleanWeatherEco/2013_MeanMonth.csv',  row.names = FALSE)
```


**THE END**