---
title: "Summary Area Bunred Compare"
author: "Anna Talucci"
date: "4/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Overview


# Packages


```{r include=FALSE}
library(sp)
library(sf)
library(rgdal) # geospatial data
library(raster)
library(rgeos) # GIS Geometry
library(foreign) # deals with dbf files
library(dplyr)
library(ggplot2)
library(cowplot)
library(RColorBrewer)
```

# Define graph Theme and color Palette 
```{r}
lb_theme = theme_bw() + theme(legend.position = "bottom") +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.line = element_line(colour = "black"))
```

```{r}
comp_theme = theme_bw() + theme(legend.position = "none") +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.line = element_line(colour = "black"))
```

```{r}
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```


# Data 

Read in shape files


```{r}
ea01 = st_read("../data/GEE-Attribute-Shapefiles-EqualArea/ea-fires-2001.shp", "ea-fires-2001") 
merc01 = st_read("../data/GEE-Attribute-Shapefiles/ru-fires-2001.shp", "ru-fires-2001") 


```



```{r}
head(ea01)
```

```{r}
head(merc01)
```




# Data prep
- pull attributes out into a data frame
- create unique id [e.g. mutate(ID =  paste(site, burn_year, transect, plot, sep = '_'))]
- combine all data tables

## Remove Geometry

```{r}
st_geometry(ea01) <- NULL
st_geometry(merc01) <- NULL
```




### Make into Dataframe

```{r}
ea01_df = as.data.frame(ea01)
merc01_df = as.data.frame(merc01)
```


```{r}
ea01_df %>%
  summarise(total_area_ha = sum(brnd_r_h))
```


```{r}
merc01_df %>%
  summarise(total_area_ha = sum(brnd_r_h))
```



```{r}
ea01_df %>% group_by(eco_cod) %>%
  summarise(total_area_ha = sum(brnd_r_h)) %>% 
        write.csv(., '../outputs/test/ea-2001.csv',  row.names = FALSE)
```


```{r}
merc01_df %>% group_by(eco_cod) %>%
  summarise(total_area_ha = sum(brnd_r_h)) %>% 
        write.csv(., '../outputs/test/mercator-2001.csv',  row.names = FALSE)
```
