---
title: "WeatherFires"
author: "Anna Talucci"
date: "6/8/2021"
output: html_document
---

# Clear workspace

```{r}
rm(list=ls()) 
```


# Overview
[Terra Climate](https://developers.google.com/earth-engine/datasets/catalog/IDAHO_EPSCOR_TERRACLIMATE#bands)

# Library
```{r include=FALSE}

library(dplyr)
library(tidyr)
library(ggplot2)
library(cowplot)
library(tidyverse)
library(broom)
library(ggplot2)
library(stringr)
library(lme4)
library(cowplot)
library(lme4)
library(lsmeans)
library(magrittr)
library(rcompanion)
library(qpcR)
```

# Define graph Theme and color Palette 

##Themes
```{r}
lb_theme = theme_bw() + theme(legend.position = "bottom") +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.line = element_line(colour = "black"))
```

```{r}
comp_theme = theme_bw() + theme(legend.position = "none") +  
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.line = element_line(colour = "black"))
```

### No Legend
```{r}
bar_theme = theme_bw() + 
  theme(legend.position = "none", legend.title = element_blank()) +
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) 
```

```{r}
bar2_theme = theme_bw() + 
  theme(panel.grid.major = element_blank()) +
    theme(axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(angle=65, vjust=0.6)) 
```


## Palettes
```{r}
cbbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r}
ecoPalette <- c("#CB453D", "#44CB30", "#2E41C3", "#36A4B4", "#B83491", "#B09C32", "#AE3D5F", "#2DC086", "#3261A1")
```




# Data 

```{r}
dfw = read.csv("../data/CombineWeather/MeanMonth2001-2020.csv") 
```

```{r}
dfw
```

# Visualize
```{r}
dfw1 = dfw %>% 
  filter(EcoCode != "SSFS") 
  
```


## CMD
```{r fig.height=7, fig.width=6}
ggplot(data = dfw1, aes(x = month, y = def, color = EcoCode)) + 
  geom_point(size = 1) +
  scale_color_manual(values=cbbPalette) +
  facet_wrap(~EcoCode, scales = "free", ncol=2 ) +
  theme_bw() +
  theme(strip.background = element_rect(color=NA, fill="white", size=1.5, linetype="solid")) 

```

```{r}
dfw2 = dfw1 %>% 
  filter(month %in% 4:9) %>%
  group_by(EcoCode, FireYr, month) %>%
  summarise(mean_def = mean(def),
            Mha = (sum(SIZEha))/1000000) %>%
  group_by(EcoCode, FireYr) %>%
  summarise(tot_def = sum(mean_def),
            Mha = min(Mha))  %>%
  mutate(log_Mha = log(Mha))

dfw2
```

```{r fig.height=7, fig.width=6}
ggplot(data = dfw2, aes(x = tot_def, y = log_Mha, color = EcoCode)) + 
  geom_smooth(method="lm", se=TRUE, alpha=0.1) +
  geom_point(size = 1) +
  scale_color_manual(values=cbbPalette) +
  facet_wrap(~EcoCode, scales = "free", ncol=2 ) +
  theme_bw() +
  theme(strip.background = element_rect(color=NA, fill="white", size=1.5, linetype="solid")) 

```


## Max Temperature


```{r}
dfw4 = dfw1 %>% 
  filter(month %in% 1:9) %>%
  group_by(EcoCode, FireYr, month) %>%
  summarise(mean_tmmx = mean(tmmx),
            Mha = (sum(SIZEha))/1000000) %>%
  group_by(EcoCode, FireYr) %>%
  summarise(max_tmmx = max(mean_tmmx),
            Mha = min(Mha))  %>%
  mutate(log_Mha = log(Mha))

dfw4
```

```{r fig.height=7, fig.width=6}
ggplot(data = dfw4, aes(x = max_tmmx, y = Mha, color = EcoCode)) + 
  geom_smooth(method="lm", se=TRUE, alpha=0.1) +
  geom_point(size = 1) +
  scale_color_manual(values=cbbPalette) +
  facet_wrap(~EcoCode, scales = "free", ncol=2 ) +
  theme_bw() +
  theme(strip.background = element_rect(color=NA, fill="white", size=1.5, linetype="solid")) 

```


# Analysis
## Model Climate Moisture Deficit
```{r}
fit1 = lm(log_Mha ~ tot_def + EcoCode +tot_def:EcoCode, data = dfw2)
```

### Summary
```{r}
summary(fit1)
```
```{r}
summary(fit1)$r.squared 
```
```{r}
int_BT = coef(fit1)[1]
int_CKMT = coef(fit1)[1] + coef(fit1)[3]
int_CPT = coef(fit1)[1] + coef(fit1)[4]
int_EST = coef(fit1)[1] + coef(fit1)[5]
int_NSCT = coef(fit1)[1] + coef(fit1)[6]
int_NST = coef(fit1)[1] + coef(fit1)[7]
int_TBBMT = coef(fit1)[1] + coef(fit1)[8]
int_TCST = coef(fit1)[1] + coef(fit1)[9]

int_BT
int_CKMT
int_CPT
int_EST
int_NSCT
int_NST
int_TBBMT
int_TCST

slope_BT = coef(fit1)[2]
slope_CKMT = coef(fit1)[2] + coef(fit1)[10]
slope_CPT = coef(fit1)[2] + coef(fit1)[11]
slope_EST = coef(fit1)[2] + coef(fit1)[12]
slope_NSCT = coef(fit1)[2] + coef(fit1)[13]
slope_NST = coef(fit1)[2] + coef(fit1)[14]
slope_TBBMT = coef(fit1)[2] + coef(fit1)[15]
slope_TCST = coef(fit1)[2] + coef(fit1)[16]

slope_BT
slope_CKMT
slope_CPT
slope_EST
slope_NSCT
slope_NST
slope_TBBMT
slope_TCST

```


### Pulling out r-squared for each group
reference: https://drsimonj.svbtle.com/running-a-model-on-separate-groups

lm(formula = biomass_log ~ ndvi + res_meters + ndvi:res_meters, 
    data = field_ndvi_long1
```{r}
 dfw2 %>% 
  nest(-EcoCode) %>% 
  mutate(fit = map(data, ~ lm(log_Mha ~ tot_def, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)
```

```{r}
 dfw2 %>% 
  nest(-EcoCode) %>% 
  mutate(fit = map(data, ~ lm(log_Mha ~ tot_def, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results) %>% 
  ggplot(aes(x = factor(EcoCode), y = r.squared)) +
    geom_bar(stat = "identity") +
    labs(x = "Climate Moisture Deficit", y = expression(R^{2}))
```

#### Residuals
```{r}
# Get the fitted value for each observation
dfw2$fit1 = fitted(fit1)
# Get the residuals of the model
dfw2$res1 = residuals(fit1)
```

```{r}
qplot(x = fit1, y = res1, data = dfw2,
main = "Residuals vs Fitted Values")
```

```{r}
qplot(x = def, y = res1, data = dfw2,
xlab = "CMD",
ylab = "Residuals",
main = "Residuals vs CMD")
```
```{r}
qplot(x = factor(1), y = res1, data = dfw2, geom = "boxplot")
```

```{r}
qqnorm(dfw2$res1, main = "Normal QQ Plot of Residuals")
qqline(dfw2$res1) # add reference line to the qq plot
```

```{r}
plot(fit1, which = 1) # residual vs fitted values
```

```{r}
plot(fit1, which = 2) # qqnorm plot of residuals
```

### Plot

```{r fig.height=5, fig.width=6}
plot_fit1 = ggplot(data = dfw2, aes(x = tot_def, y = log_Mha, color = EcoCode)) + 
  geom_smooth(method="lm", se=TRUE, alpha=0.1) +
  geom_point(size = 1) +
  scale_color_manual(values=cbbPalette) +
    labs(y=expression(atop("Log-transformed Mha")), x= "Climate Moisture Deficit", color = "Buffer resolution") +
  theme_bw() + 
  theme(legend.position = "bottom") +
  guides(colour = guide_legend(nrow = 1))

plot_fit1
  
```

```{r}
plot_fit1.1 = ggplot(data = field_ndvi_long1, aes(x = ndvi, y = biomass_log, color = res_meters)) + 
  geom_smooth(method="lm", se=TRUE, alpha=0.1) +
  geom_point(size = 1) +
  scale_color_manual(values=cbbPalette) +
    labs(y=expression(atop("Log-transformed C biomass", paste((g~C~m^-2)))), x= "NDVI", color = "Buffer resolution") +
  reg_theme

plot_fit1.1
  
```

```{r eval=FALSE, include=FALSE}
ggsave("../figures/2020-08-19_ndvi-biomass-resolution.jpeg", plot = plot_fit1, width = 6, height = 5, units = c("in"), dpi=600 )
```


## Model Precip


**THE END**